### ISSUE TITLE
Use LangGraph

### ISSUE THREAD

**Issue by camronh** [camronh/promptnado#12]
Not sure the added benefit to this one. Cleans up the traces?

**Comment by camronh** [comment]
LangGraph cloud

**Comment by lgesuellip** [comment]
Hi Cam,

I could create a new branch to start migrating the code to LangGraph. Do you have any ideas, diagrams, or specific approaches in mind?

**Comment by camronh** [comment]
> Hi Cam,
> 
> 
> 
> I could create a new branch to start migrating the code to LangGraph. Do you have any ideas, diagrams, or specific approaches in mind?

Hey! I implemented LangGraph over the weekend! It's already taken care of. Thanks
